# CMake generated Testfile for 
# Source directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form
# Build directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/minimal-examples-lowlevel/http-client/minimal-http-client-post-form
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(st_hcpf_srv "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/scripts/ctest-background.sh" "hcpf_srv" "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/libwebsockets-test-server" "-r" "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/share/libwebsockets-test-server/" "-s" "--port" "7340")
set_tests_properties(st_hcpf_srv PROPERTIES  FIXTURES_SETUP "hcpf_srv" TIMEOUT "800" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;61;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
add_test(ki_hcpf_srv "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/scripts/ctest-background-kill.sh" "hcpf_srv" "libwebsockets-test-server" "--port" "7340")
set_tests_properties(ki_hcpf_srv PROPERTIES  FIXTURES_CLEANUP "hcpf_srv" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;67;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
add_test(http-client-post-form "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post-form" "-l" "https://localhost:7340/formtest")
set_tests_properties(http-client-post-form PROPERTIES  FIXTURES_REQUIRED "hcpf_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;80;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
add_test(http-client-post-form-m "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post-form" "-l" "-m" "https://localhost:7340/formtest")
set_tests_properties(http-client-post-form-m PROPERTIES  FIXTURES_REQUIRED "hcpf_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;82;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
add_test(http-client-post-form-h1 "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post-form" "-l" "--h1" "https://localhost:7340/formtest")
set_tests_properties(http-client-post-form-h1 PROPERTIES  FIXTURES_REQUIRED "hcpf_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;84;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
add_test(http-client-post-form-m-h1 "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post-form" "-l" "-m" "--h1" "https://localhost:7340/formtest")
set_tests_properties(http-client-post-form-m-h1 PROPERTIES  FIXTURES_REQUIRED "hcpf_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;86;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post-form/CMakeLists.txt;0;")
