# CMake generated Testfile for 
# Source directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post
# Build directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/minimal-examples-lowlevel/http-client/minimal-http-client-post
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(st_hcp_srv "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/scripts/ctest-background.sh" "hcp_srv" "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/libwebsockets-test-server" "-r" "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/share/libwebsockets-test-server/" "-s" "--port" "7040")
set_tests_properties(st_hcp_srv PROPERTIES  FIXTURES_SETUP "hcp_srv" TIMEOUT "800" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;61;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
add_test(ki_hcp_srv "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/scripts/ctest-background-kill.sh" "hcp_srv" "libwebsockets-test-server" "--port" "7040")
set_tests_properties(ki_hcp_srv PROPERTIES  FIXTURES_CLEANUP "hcp_srv" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;67;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
add_test(http-client-post "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post" "-l" "https://localhost:7040/formtest")
set_tests_properties(http-client-post PROPERTIES  FIXTURES_REQUIRED "hcp_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;80;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
add_test(http-client-post-m "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post" "-l" "-m" "https://localhost:7040/formtest")
set_tests_properties(http-client-post-m PROPERTIES  FIXTURES_REQUIRED "hcp_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;82;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
add_test(http-client-post-h1 "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post" "-l" "--h1" "https://localhost:7040/formtest")
set_tests_properties(http-client-post-h1 PROPERTIES  FIXTURES_REQUIRED "hcp_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;84;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
add_test(http-client-post-m-h1 "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-post" "-l" "-m" "--h1" "https://localhost:7040/formtest")
set_tests_properties(http-client-post-m-h1 PROPERTIES  FIXTURES_REQUIRED "hcp_srv" TIMEOUT "20" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;86;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-post/CMakeLists.txt;0;")
