# CMake generated Testfile for 
# Source directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow
# Build directory: /mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(http-client-h2-rxflow-warmcat "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-h2-rxflow")
set_tests_properties(http-client-h2-rxflow-warmcat PROPERTIES  TIMEOUT "30" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow/CMakeLists.txt;20;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow/CMakeLists.txt;0;")
add_test(http-client-h2-rxflow-warmcat-h1 "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/build-linux/bin/lws-minimal-http-client-h2-rxflow" "--h1")
set_tests_properties(http-client-h2-rxflow-warmcat-h1 PROPERTIES  TIMEOUT "30" WORKING_DIRECTORY "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow" _BACKTRACE_TRIPLES "/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow/CMakeLists.txt;21;add_test;/mnt/c/Users/G/Desktop/Builds/sigilnet/packages/QWormhole/libwebsockets/minimal-examples-lowlevel/http-client/minimal-http-client-h2-rxflow/CMakeLists.txt;0;")
